
version: '3'
services:
  web:
    image: tomcat
    ports: 
      - "8083:8080"
    volumes:
      - ./target/odata2sparql.v4.war:/usr/local/tomcat/webapps/ROOT.war
      - ./target/odata2sparql.v4:/usr/local/tomcat/webapps/ROOT
